# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [16]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [6]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
print(np.version)

<module 'numpy.version' from '/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/numpy/version.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
import numpy as np

x = np.empty(10)

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [20]:
import numpy as np
x = np.zeros(10)

print(x)
print(x.nbytes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [21]:
import numpy as np

np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_lik

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [23]:
import numpy as np
x = np.zeros(10)
x[3]=1

print(x)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
import numpy as np 

x = np.random.randint(10, 50, 10)
print(x)

[47 14 10 24 45 17 39 38 25 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [28]:
import numpy as np 

x = np.random.randint(10, 50, 10)
print(x)
print(np.flip(x))

[14 23 44 25 42 22 31 39 28 21]
[21 28 39 31 22 42 25 44 23 14]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
import numpy as np 

x = np.random.randint(0, 9, (3,3))
print(x)

[[0 0 4]
 [2 8 5]
 [3 1 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [30]:
import numpy as np
x = np.array([1,2,0,0,4,0])
y = np.where(x==0)
print(y)

(array([2, 3, 5]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [33]:
import numpy as np

x= np.identity(3)

print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [34]:
import numpy as np

x = np.random.randint(0,10,(3,3,3))

print(x)

[[[5 5 4]
  [4 5 2]
  [8 7 6]]

 [[0 9 1]
  [5 2 0]
  [1 4 7]]

 [[7 9 1]
  [8 8 9]
  [5 0 8]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
import numpy as np

x = np.random.randint(0,10,(10,10))

print(x.min(),x.max())

0 9


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [42]:
import numpy as np
x = np.random.randint(0,100,30)

print(x)

#np.info(x.mean)
print(x.mean(axis=0,keepdims=True))

[57 28 31 93  2 75 24 13 25 18  4 32 61 80 15 52 54 98 32 71 94 61 56 82
 49 65 53 82 66 61]
[51.13333333]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [48]:
import numpy as np

x = np.ones((7,7))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [57]:
import numpy as np 

x = np.random.randint(0,10,(3,3))

print(x)

x = np.pad(x,1,mode='constant',constant_values=0)

print(x)

[[4 0 1]
 [7 3 7]
 [7 5 7]]
[[0 0 0 0 0]
 [0 4 0 1 0]
 [0 7 3 7 0]
 [0 7 5 7 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [70]:
0 * np.nan # nan
np.nan == np.nan #false
np.inf > np.nan # false
np.nan - np.nan #nan 
np.nan in set([np.nan]) #true
0.3 == 3 * 0.1 # false

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [73]:
import numpy as np

# np.info(np.diag)

x = np.diag(np.arange(1,5),k=-1)

print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [99]:
import numpy as np

x = np.zeros((8,8))

x[1::2,0::2] = 1
x[0::2,1::2] = 1

print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [103]:
// m[5,5,4]

336


IndexError: index 100 is out of bounds for axis 0 with size 6

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [104]:
import numpy as np

x1 = np.random.randint(0,10,(5,3))
x2 = np.random.randint(0,10,(3,2))

x = np.dot(x1,x2)

print(x1)
print(x2)
print(x)

[[4 4 0]
 [4 4 3]
 [3 0 0]
 [1 8 6]
 [2 0 6]]
[[1 6]
 [9 5]
 [3 9]]
[[ 40  44]
 [ 49  71]
 [  3  18]
 [ 91 100]
 [ 20  66]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [106]:
import numpy as np

v = np.random.randint(0,10,10)

print(v)
v[2:8]=-v[2:8]
print(v)

[6 0 5 5 6 3 4 1 5 8]
[ 6  0 -5 -5 -6 -3 -4 -1  5  8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [126]:
import numpy as np
10 == np.sum(range(5),-1)

True

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [129]:
import numpy as np
np.array([np.nan]).astype(int).astype(float)

array([nan])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
x= x//1
x=x.astype(int)

#### 30. How to find common values between two arrays? (★☆☆)

In [130]:
import numpy as np
  
  
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = [1, 3, 4]
  
# Common values between two arrays
print(np.intersect1d(ar1, ar2))

[1 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [4]:
import numpy as np
#np.seterr(all="ignore")
np.seterr(all="warn")

{'divide': 'warn', 'over': 'warn', 'under': 'warn', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [136]:
np.sqrt(-1) == np.emath.sqrt(-1)

print(np.emath.sqrt(-1))

nan


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [11]:
import numpy as np

today = np.datetime64('today', 'D')

delta = np.timedelta64(1,'D')

print(today)
# print(delta)
yesterday = today - delta
print(yesterday)
print(today + delta)

2021-12-28
1 days
2021-12-27
2021-12-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [16]:
import numpy as np

x = np.arange('2016-06','2016-07',dtype='datetime64[D]')
print(x)

['2016-06-01' '2016-06-02' '2016-06-03' '2016-06-04' '2016-06-05'
 '2016-06-06' '2016-06-07' '2016-06-08' '2016-06-09' '2016-06-10'
 '2016-06-11' '2016-06-12' '2016-06-13' '2016-06-14' '2016-06-15'
 '2016-06-16' '2016-06-17' '2016-06-18' '2016-06-19' '2016-06-20'
 '2016-06-21' '2016-06-22' '2016-06-23' '2016-06-24' '2016-06-25'
 '2016-06-26' '2016-06-27' '2016-06-28' '2016-06-29' '2016-06-30']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [20]:
import numpy as np

a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))

print(a)
print('----------')
print(b)



[[5 1 6]
 [9 4 3]
 [0 9 8]]
----------
[[1 5 0]
 [0 3 3]
 [1 1 4]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)